spec_version: 5.0.0
type: app

name: casting-defect-detection
title: Casting Defect Detection
version: 1.0.1
description: Detects defects in casting products using a Computer Vision model
category: smartapp

flags:
  enable_runtime_update:
    configuration: false
    resources: false
    parameters: true
    resource_properties: true

data_streams:
  inputs:
    - name: camera-feed
      data_type: camera-image
