# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/5.0.0/app/app.json

# YAML (Structure) Spec Version
spec_version: 5.0.0
# Type
type: exporter

# Info
name: microsoft-teams-sender
title: Microsoft Teams Sender
description: This exporter handles Teams Message custom actions and sends Microsoft Teams messages to a given channel
version: 0.0.1

# Capabilities
flags:
  enable_runtime_update:
    configuration: false # Reload Application Configuration in runtime

# Custom Actions
custom_actions:
  inputs:
    - type: Teams Message

# UI JSON schemas (Optional)
ui_schemas:
  # Application Configuration Schema
  configuration: "ui_schemas/configuration.json"
  # Custom Action Payload Schemas (keyed by action type)
  custom_actions:
    Teams Message: "ui_schemas/teams_message.json"

# Defaults (Runtime/Deployment)
defaults:
  # Application Configuration Default Values
  configuration:
    webhooks:
      - channel: test
        url: <% secrets.teams-webhook-test %>

  # System Settings
  system: {}
