# YAML (Structure) Spec Version
spec_version: 5.0.0
# Type
type: exporter

# Info
name: resnet-issue-creation
title: Resnet Issue Creation
description: This exporter handles custom-defined actions that trigger issue creation in Resnet.
version: 1.0.15

# Capabilities
flags:
  enable_runtime_update:
    configuration: false # Reload Application Configuration in runtime

# Custom Actions
custom_actions:
  inputs:
    - type: Resnet Issue

# UI JSON schemas (Optional)
ui_schemas:
  # Application Configuration Schema
  configuration: "ui_schemas/configuration.json"

# Defaults (Runtime/Deployment)
defaults:
  # Application Configuration Default Values
  configuration:
    url: https://api.resnet.ai/v1-beta1/entities/issue
    tenant: <tenant>
    api_key: <api_key>

  # System Settings
  system: {}
