info:
  description: Monitors if a motor is overheating. If so, it will send a Control Change/Recommendation to reduce the Motor Speed.
  name: event-detection
  title: Event Detection
  version: 1.0.0

spec_version: 4.12.0

app:
  type: kelvin
  kelvin:
    inputs:
    - data_type: number
      name: motor_temperature

    outputs:
    - name: motor_speed_set_point
      data_type: number
      control_change: true

    parameters:
    - name: closed_loop
      data_type: boolean
      default:
        value: false
      schema:
        title: "Closed Loop"
    - name: speed_decrease_set_point
      data_type: number
      default:
        value: 1000
      schema:
        title: "Speed Decrease SetPoint"
        minimum: 1000
        maximum: 3000
    - name: temperature_max_threshold
      data_type: number
      default:
        value: 59
      schema:
        title: "Temperature Max Threshold"
        minimum: 50
        maximum: 100
    
    language:
      python:
        entry_point: kelvin_python_sdk
      type: python

system:
  environment_vars:
  - name: KELVIN_GW_MODE
    value: SOCKETS
