info:
  description: Monitors if a motor is overheating. If so, it will send a Control Change to reduce the Motor Speed.
  name: event-detection
  title: Event Detection
  version: 1.0.0

spec_version: 4.12.0

app:
  type: kelvin
  kelvin:
    
    inputs:
    - data_type: number
      name: motor_temperature

    outputs:
    - data_type: number
      name: motor_speed_set_point
      control_change: true

    language:
      python:
        entry_point: kelvin_python_sdk
      type: python

system:
  environment_vars:
  - name: KELVIN_GW_MODE
    value: SOCKETS
