spec_version: 5.0.0
type: app

name: multi-objective-optimization-ml
title: Multi-Objective Optimization ML
description: multi-objective-optimization-ml
version: 1.0.0
category: smartapp

flags:
  enable_runtime_update:
    configuration: false
    assets: false
    resource_parameters: true
    resource_properties: true

data_streams:
  inputs:
    - name: wire_part_vacuum_foil_level_set_point
      data_type: number
    - name: exhaust_fan_3_burner_temperature_set_point
      data_type: number
    - name: paper_machine_speed_set_point
      data_type: number
    - name: primary_screen_reject_flow_rate_set_point
      data_type: number
    - name: turbo_3_vacuum_control_output_set_point
      data_type: number
    - name: shoe_press_hydration_tank_level
      data_type: number
    - name: low_pressure_steam_flow_rate_set_point
      data_type: number
    - name: air_dryer_temperature_set_point
      data_type: number
    - name: jw_ratio_volume_flow
      data_type: number
    - name: 3p_load_top_side_set_point
      data_type: number
    - name: mix_pipe_flow_set_point
      data_type: number
    - name: top_dryers_steam_pressure_set_point
      data_type: number
    - name: spray_starch_standby_pump_rate_set_point
      data_type: number
    - name: paper_substance_weight
      data_type: number
    - name: paper_brightness_top_side
      data_type: number
    - name: luminance_value_top_side
      data_type: number
    - name: luminance_value_bottom_side
      data_type: number
