# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/4.12.0/app/app.json
spec_version: 4.12.0
info:
  name: camera-connector
  title: Camera Connector
  version: 1.0.2
  description: Publishes camera feed images to Kelvin Platform
app:
  type: kelvin
  kelvin:
    language:
      type: python
      python:
        entry_point: kelvin_python_sdk
    inputs: []
    outputs:
      - name: camera-feed
        data_type: string
    configuration: {}
    parameters: []
system:
  environment_vars:
    - name: KELVIN_GW_MODE
      value: SOCKETS
