# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/4.12.0/app/app.json
spec_version: 4.12.0
info:
  name: databricks-delta-table
  title: Databricks Delta Table
  version: 1.0.0
  description: Establishes a connection with a DataBricks Delta Table and generates Kelvin Recommendations at regular intervals.
app:
  type: kelvin
  kelvin:
    language:
      type: python
      python:
        entry_point: kelvin_python_sdk
    inputs: []
    outputs:
      - name: motor_speed_set_point
        data_type: number
    configuration:
      polling_interval: 60
    parameters: []
system:
  environment_vars:
    - name: KELVIN_GW_MODE
      value: SOCKETS
    - name: DATABRICKS_SERVER_HOSTNAME
      value: <% secrets.databricks-server-hostname %>
    - name: DATABRICKS_HTTP_PATH
      value: <% secrets.databricks-http-path %>
    - name: DATABRICKS_ACCESS_TOKEN
      value: <% secrets.databricks-access-token %>
